// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: protocol/game/client_protocol.proto

package game_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardState int32

const (
	CardState_DISABLED CardState = 0
	CardState_ENABLED  CardState = 1
)

// Enum value maps for CardState.
var (
	CardState_name = map[int32]string{
		0: "DISABLED",
		1: "ENABLED",
	}
	CardState_value = map[string]int32{
		"DISABLED": 0,
		"ENABLED":  1,
	}
)

func (x CardState) Enum() *CardState {
	p := new(CardState)
	*p = x
	return p
}

func (x CardState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardState) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_game_client_protocol_proto_enumTypes[0].Descriptor()
}

func (CardState) Type() protoreflect.EnumType {
	return &file_protocol_game_client_protocol_proto_enumTypes[0]
}

func (x CardState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardState.Descriptor instead.
func (CardState) EnumDescriptor() ([]byte, []int) {
	return file_protocol_game_client_protocol_proto_rawDescGZIP(), []int{0}
}

type GameClientProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *GameProtocolHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PlayerPov *PlayerPov          `protobuf:"bytes,2,opt,name=player_pov,json=playerPov,proto3" json:"player_pov,omitempty"`
}

func (x *GameClientProtocol) Reset() {
	*x = GameClientProtocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_client_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameClientProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameClientProtocol) ProtoMessage() {}

func (x *GameClientProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_client_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameClientProtocol.ProtoReflect.Descriptor instead.
func (*GameClientProtocol) Descriptor() ([]byte, []int) {
	return file_protocol_game_client_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *GameClientProtocol) GetHeader() *GameProtocolHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GameClientProtocol) GetPlayerPov() *PlayerPov {
	if x != nil {
		return x.PlayerPov
	}
	return nil
}

type PlayerPov struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team_1Score  uint32      `protobuf:"varint,1,opt,name=team_1_score,json=team1Score,proto3" json:"team_1_score,omitempty"`
	Team_2Score  uint32      `protobuf:"varint,2,opt,name=team_2_score,json=team2Score,proto3" json:"team_2_score,omitempty"`
	Team_1Points uint32      `protobuf:"varint,3,opt,name=team_1_points,json=team1Points,proto3" json:"team_1_points,omitempty"`
	Team_2Points uint32      `protobuf:"varint,4,opt,name=team_2_points,json=team2Points,proto3" json:"team_2_points,omitempty"`
	HandCards    []*HandCard `protobuf:"bytes,5,rep,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"`
	PlayedCards  []*Card     `protobuf:"bytes,6,rep,name=played_cards,json=playedCards,proto3" json:"played_cards,omitempty"`
	Auction      *Auction    `protobuf:"bytes,7,opt,name=auction,proto3,oneof" json:"auction,omitempty"`
	Trump        *CardSuit   `protobuf:"varint,8,opt,name=trump,proto3,enum=protocol.CardSuit,oneof" json:"trump,omitempty"`
	CheatButton  bool        `protobuf:"varint,9,opt,name=cheat_button,json=cheatButton,proto3" json:"cheat_button,omitempty"`
}

func (x *PlayerPov) Reset() {
	*x = PlayerPov{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_client_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerPov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPov) ProtoMessage() {}

func (x *PlayerPov) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_client_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPov.ProtoReflect.Descriptor instead.
func (*PlayerPov) Descriptor() ([]byte, []int) {
	return file_protocol_game_client_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerPov) GetTeam_1Score() uint32 {
	if x != nil {
		return x.Team_1Score
	}
	return 0
}

func (x *PlayerPov) GetTeam_2Score() uint32 {
	if x != nil {
		return x.Team_2Score
	}
	return 0
}

func (x *PlayerPov) GetTeam_1Points() uint32 {
	if x != nil {
		return x.Team_1Points
	}
	return 0
}

func (x *PlayerPov) GetTeam_2Points() uint32 {
	if x != nil {
		return x.Team_2Points
	}
	return 0
}

func (x *PlayerPov) GetHandCards() []*HandCard {
	if x != nil {
		return x.HandCards
	}
	return nil
}

func (x *PlayerPov) GetPlayedCards() []*Card {
	if x != nil {
		return x.PlayedCards
	}
	return nil
}

func (x *PlayerPov) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

func (x *PlayerPov) GetTrump() CardSuit {
	if x != nil && x.Trump != nil {
		return *x.Trump
	}
	return CardSuit_ROSU
}

func (x *PlayerPov) GetCheatButton() bool {
	if x != nil {
		return x.CheatButton
	}
	return false
}

type HandCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card  *Card     `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	State CardState `protobuf:"varint,2,opt,name=state,proto3,enum=protocol.CardState" json:"state,omitempty"`
}

func (x *HandCard) Reset() {
	*x = HandCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_client_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandCard) ProtoMessage() {}

func (x *HandCard) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_client_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandCard.ProtoReflect.Descriptor instead.
func (*HandCard) Descriptor() ([]byte, []int) {
	return file_protocol_game_client_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *HandCard) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *HandCard) GetState() CardState {
	if x != nil {
		return x.State
	}
	return CardState_DISABLED
}

type Auction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Visible bool   `protobuf:"varint,1,opt,name=visible,proto3" json:"visible,omitempty"`
	Bids    []*Bid `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	MaxBid  uint32 `protobuf:"varint,3,opt,name=max_bid,json=maxBid,proto3" json:"max_bid,omitempty"`
}

func (x *Auction) Reset() {
	*x = Auction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_client_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_client_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_protocol_game_client_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *Auction) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Auction) GetBids() []*Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Auction) GetMaxBid() uint32 {
	if x != nil {
		return x.MaxBid
	}
	return 0
}

type Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasBid bool   `protobuf:"varint,1,opt,name=has_bid,json=hasBid,proto3" json:"has_bid,omitempty"`
	Value  uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Bid) Reset() {
	*x = Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_client_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_client_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_protocol_game_client_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *Bid) GetHasBid() bool {
	if x != nil {
		return x.HasBid
	}
	return false
}

func (x *Bid) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_protocol_game_client_protocol_proto protoreflect.FileDescriptor

var file_protocol_game_client_protocol_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x1a,
	0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x6d, 0x69, 0x73, 0x63, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7e, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x34, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x32, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x76, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x76, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x50, 0x6f, 0x76, 0x22, 0x97, 0x03, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x50, 0x6f, 0x76, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x31, 0x5f, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x65, 0x61, 0x6d, 0x31,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x32, 0x5f,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x65, 0x61,
	0x6d, 0x32, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x31, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x74, 0x65, 0x61, 0x6d, 0x31, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x74,
	0x65, 0x61, 0x6d, 0x5f, 0x32, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x74, 0x65, 0x61, 0x6d, 0x32, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x31, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x48,
	0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x31, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x61, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x05, 0x74, 0x72, 0x75, 0x6d, 0x70,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x75, 0x69, 0x74, 0x48, 0x01, 0x52, 0x05, 0x74, 0x72,
	0x75, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x65, 0x61, 0x74, 0x5f,
	0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x68,
	0x65, 0x61, 0x74, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x61, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x72, 0x75, 0x6d, 0x70, 0x22,
	0x59, 0x0a, 0x08, 0x48, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x63,
	0x61, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12,
	0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5f, 0x0a, 0x07, 0x41, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12,
	0x21, 0x0a, 0x04, 0x62, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x04, 0x62, 0x69,
	0x64, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x6d, 0x61, 0x78, 0x42, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x03, 0x42,
	0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x5f, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x06, 0x68, 0x61, 0x73, 0x42, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x2a, 0x26, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c,
	0x0a, 0x08, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07,
	0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45, 0x44, 0x10, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x2e, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_game_client_protocol_proto_rawDescOnce sync.Once
	file_protocol_game_client_protocol_proto_rawDescData = file_protocol_game_client_protocol_proto_rawDesc
)

func file_protocol_game_client_protocol_proto_rawDescGZIP() []byte {
	file_protocol_game_client_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_game_client_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_game_client_protocol_proto_rawDescData)
	})
	return file_protocol_game_client_protocol_proto_rawDescData
}

var file_protocol_game_client_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protocol_game_client_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protocol_game_client_protocol_proto_goTypes = []interface{}{
	(CardState)(0),             // 0: protocol.CardState
	(*GameClientProtocol)(nil), // 1: protocol.GameClientProtocol
	(*PlayerPov)(nil),          // 2: protocol.PlayerPov
	(*HandCard)(nil),           // 3: protocol.HandCard
	(*Auction)(nil),            // 4: protocol.Auction
	(*Bid)(nil),                // 5: protocol.Bid
	(*GameProtocolHeader)(nil), // 6: protocol.GameProtocolHeader
	(*Card)(nil),               // 7: protocol.Card
	(CardSuit)(0),              // 8: protocol.CardSuit
}
var file_protocol_game_client_protocol_proto_depIdxs = []int32{
	6, // 0: protocol.GameClientProtocol.header:type_name -> protocol.GameProtocolHeader
	2, // 1: protocol.GameClientProtocol.player_pov:type_name -> protocol.PlayerPov
	3, // 2: protocol.PlayerPov.hand_cards:type_name -> protocol.HandCard
	7, // 3: protocol.PlayerPov.played_cards:type_name -> protocol.Card
	4, // 4: protocol.PlayerPov.auction:type_name -> protocol.Auction
	8, // 5: protocol.PlayerPov.trump:type_name -> protocol.CardSuit
	7, // 6: protocol.HandCard.card:type_name -> protocol.Card
	0, // 7: protocol.HandCard.state:type_name -> protocol.CardState
	5, // 8: protocol.Auction.bids:type_name -> protocol.Bid
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_protocol_game_client_protocol_proto_init() }
func file_protocol_game_client_protocol_proto_init() {
	if File_protocol_game_client_protocol_proto != nil {
		return
	}
	file_protocol_game_header_proto_init()
	file_protocol_game_misc_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_protocol_game_client_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameClientProtocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_client_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerPov); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_client_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_client_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_client_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocol_game_client_protocol_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_game_client_protocol_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_game_client_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_game_client_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_game_client_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_game_client_protocol_proto_msgTypes,
	}.Build()
	File_protocol_game_client_protocol_proto = out.File
	file_protocol_game_client_protocol_proto_rawDesc = nil
	file_protocol_game_client_protocol_proto_goTypes = nil
	file_protocol_game_client_protocol_proto_depIdxs = nil
}
