// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: protocol/game/misc.proto

package game_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardSuit int32

const (
	CardSuit_ROSU   CardSuit = 0
	CardSuit_DUBA   CardSuit = 1
	CardSuit_VERDE  CardSuit = 2
	CardSuit_GHINDA CardSuit = 3
)

// Enum value maps for CardSuit.
var (
	CardSuit_name = map[int32]string{
		0: "ROSU",
		1: "DUBA",
		2: "VERDE",
		3: "GHINDA",
	}
	CardSuit_value = map[string]int32{
		"ROSU":   0,
		"DUBA":   1,
		"VERDE":  2,
		"GHINDA": 3,
	}
)

func (x CardSuit) Enum() *CardSuit {
	p := new(CardSuit)
	*p = x
	return p
}

func (x CardSuit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardSuit) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_game_misc_proto_enumTypes[0].Descriptor()
}

func (CardSuit) Type() protoreflect.EnumType {
	return &file_protocol_game_misc_proto_enumTypes[0]
}

func (x CardSuit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardSuit.Descriptor instead.
func (CardSuit) EnumDescriptor() ([]byte, []int) {
	return file_protocol_game_misc_proto_rawDescGZIP(), []int{0}
}

type CardValue int32

const (
	CardValue_ACE   CardValue = 0
	CardValue_TEN   CardValue = 1
	CardValue_KING  CardValue = 2
	CardValue_QUEEN CardValue = 3
	CardValue_JACK  CardValue = 4
	CardValue_NINE  CardValue = 5
)

// Enum value maps for CardValue.
var (
	CardValue_name = map[int32]string{
		0: "ACE",
		1: "TEN",
		2: "KING",
		3: "QUEEN",
		4: "JACK",
		5: "NINE",
	}
	CardValue_value = map[string]int32{
		"ACE":   0,
		"TEN":   1,
		"KING":  2,
		"QUEEN": 3,
		"JACK":  4,
		"NINE":  5,
	}
)

func (x CardValue) Enum() *CardValue {
	p := new(CardValue)
	*p = x
	return p
}

func (x CardValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardValue) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_game_misc_proto_enumTypes[1].Descriptor()
}

func (CardValue) Type() protoreflect.EnumType {
	return &file_protocol_game_misc_proto_enumTypes[1]
}

func (x CardValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardValue.Descriptor instead.
func (CardValue) EnumDescriptor() ([]byte, []int) {
	return file_protocol_game_misc_proto_rawDescGZIP(), []int{1}
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suit  CardSuit  `protobuf:"varint,1,opt,name=suit,proto3,enum=protocol.CardSuit" json:"suit,omitempty"`
	Value CardValue `protobuf:"varint,2,opt,name=value,proto3,enum=protocol.CardValue" json:"value,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_misc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_misc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_protocol_game_misc_proto_rawDescGZIP(), []int{0}
}

func (x *Card) GetSuit() CardSuit {
	if x != nil {
		return x.Suit
	}
	return CardSuit_ROSU
}

func (x *Card) GetValue() CardValue {
	if x != nil {
		return x.Value
	}
	return CardValue_ACE
}

var File_protocol_game_misc_proto protoreflect.FileDescriptor

var file_protocol_game_misc_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x6d, 0x69, 0x73, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x59, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x04,
	0x73, 0x75, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x75, 0x69, 0x74, 0x52, 0x04,
	0x73, 0x75, 0x69, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43,
	0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a,
	0x35, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x64, 0x53, 0x75, 0x69, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x52,
	0x4f, 0x53, 0x55, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x55, 0x42, 0x41, 0x10, 0x01, 0x12,
	0x09, 0x0a, 0x05, 0x56, 0x45, 0x52, 0x44, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x48,
	0x49, 0x4e, 0x44, 0x41, 0x10, 0x03, 0x2a, 0x46, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x43, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03,
	0x54, 0x45, 0x4e, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12,
	0x09, 0x0a, 0x05, 0x51, 0x55, 0x45, 0x45, 0x4e, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x41,
	0x43, 0x4b, 0x10, 0x04, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x49, 0x4e, 0x45, 0x10, 0x05, 0x42, 0x24,
	0x5a, 0x22, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_game_misc_proto_rawDescOnce sync.Once
	file_protocol_game_misc_proto_rawDescData = file_protocol_game_misc_proto_rawDesc
)

func file_protocol_game_misc_proto_rawDescGZIP() []byte {
	file_protocol_game_misc_proto_rawDescOnce.Do(func() {
		file_protocol_game_misc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_game_misc_proto_rawDescData)
	})
	return file_protocol_game_misc_proto_rawDescData
}

var file_protocol_game_misc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protocol_game_misc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_game_misc_proto_goTypes = []interface{}{
	(CardSuit)(0),  // 0: protocol.CardSuit
	(CardValue)(0), // 1: protocol.CardValue
	(*Card)(nil),   // 2: protocol.Card
}
var file_protocol_game_misc_proto_depIdxs = []int32{
	0, // 0: protocol.Card.suit:type_name -> protocol.CardSuit
	1, // 1: protocol.Card.value:type_name -> protocol.CardValue
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocol_game_misc_proto_init() }
func file_protocol_game_misc_proto_init() {
	if File_protocol_game_misc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_game_misc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_game_misc_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_game_misc_proto_goTypes,
		DependencyIndexes: file_protocol_game_misc_proto_depIdxs,
		EnumInfos:         file_protocol_game_misc_proto_enumTypes,
		MessageInfos:      file_protocol_game_misc_proto_msgTypes,
	}.Build()
	File_protocol_game_misc_proto = out.File
	file_protocol_game_misc_proto_rawDesc = nil
	file_protocol_game_misc_proto_goTypes = nil
	file_protocol_game_misc_proto_depIdxs = nil
}
