// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: protocol/game/protocol.proto

package game_protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CardSuit int32

const (
	CardSuit_ROSU   CardSuit = 0
	CardSuit_DUBA   CardSuit = 1
	CardSuit_VERDE  CardSuit = 2
	CardSuit_GHINDA CardSuit = 3
)

// Enum value maps for CardSuit.
var (
	CardSuit_name = map[int32]string{
		0: "ROSU",
		1: "DUBA",
		2: "VERDE",
		3: "GHINDA",
	}
	CardSuit_value = map[string]int32{
		"ROSU":   0,
		"DUBA":   1,
		"VERDE":  2,
		"GHINDA": 3,
	}
)

func (x CardSuit) Enum() *CardSuit {
	p := new(CardSuit)
	*p = x
	return p
}

func (x CardSuit) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardSuit) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_game_protocol_proto_enumTypes[0].Descriptor()
}

func (CardSuit) Type() protoreflect.EnumType {
	return &file_protocol_game_protocol_proto_enumTypes[0]
}

func (x CardSuit) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardSuit.Descriptor instead.
func (CardSuit) EnumDescriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{0}
}

type CardValue int32

const (
	CardValue_ACE   CardValue = 0
	CardValue_TEN   CardValue = 1
	CardValue_KING  CardValue = 2
	CardValue_QUEEN CardValue = 3
	CardValue_JACK  CardValue = 4
	CardValue_NINE  CardValue = 5
)

// Enum value maps for CardValue.
var (
	CardValue_name = map[int32]string{
		0: "ACE",
		1: "TEN",
		2: "KING",
		3: "QUEEN",
		4: "JACK",
		5: "NINE",
	}
	CardValue_value = map[string]int32{
		"ACE":   0,
		"TEN":   1,
		"KING":  2,
		"QUEEN": 3,
		"JACK":  4,
		"NINE":  5,
	}
)

func (x CardValue) Enum() *CardValue {
	p := new(CardValue)
	*p = x
	return p
}

func (x CardValue) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardValue) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_game_protocol_proto_enumTypes[1].Descriptor()
}

func (CardValue) Type() protoreflect.EnumType {
	return &file_protocol_game_protocol_proto_enumTypes[1]
}

func (x CardValue) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardValue.Descriptor instead.
func (CardValue) EnumDescriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{1}
}

type CardState int32

const (
	CardState_DISABLED CardState = 0
	CardState_ENABLED  CardState = 1
)

// Enum value maps for CardState.
var (
	CardState_name = map[int32]string{
		0: "DISABLED",
		1: "ENABLED",
	}
	CardState_value = map[string]int32{
		"DISABLED": 0,
		"ENABLED":  1,
	}
)

func (x CardState) Enum() *CardState {
	p := new(CardState)
	*p = x
	return p
}

func (x CardState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CardState) Descriptor() protoreflect.EnumDescriptor {
	return file_protocol_game_protocol_proto_enumTypes[2].Descriptor()
}

func (CardState) Type() protoreflect.EnumType {
	return &file_protocol_game_protocol_proto_enumTypes[2]
}

func (x CardState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CardState.Descriptor instead.
func (CardState) EnumDescriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{2}
}

type GameServerProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *GameProtocolHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (x *GameServerProtocol) Reset() {
	*x = GameServerProtocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_protocol_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameServerProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServerProtocol) ProtoMessage() {}

func (x *GameServerProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_protocol_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServerProtocol.ProtoReflect.Descriptor instead.
func (*GameServerProtocol) Descriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *GameServerProtocol) GetHeader() *GameProtocolHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type GameClientProtocol struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *GameProtocolHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	PlayerPov *PlayerPov          `protobuf:"bytes,2,opt,name=player_pov,json=playerPov,proto3" json:"player_pov,omitempty"`
}

func (x *GameClientProtocol) Reset() {
	*x = GameClientProtocol{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_protocol_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameClientProtocol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameClientProtocol) ProtoMessage() {}

func (x *GameClientProtocol) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_protocol_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameClientProtocol.ProtoReflect.Descriptor instead.
func (*GameClientProtocol) Descriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *GameClientProtocol) GetHeader() *GameProtocolHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GameClientProtocol) GetPlayerPov() *PlayerPov {
	if x != nil {
		return x.PlayerPov
	}
	return nil
}

type GameProtocolHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataLength uint32 `protobuf:"varint,1,opt,name=data_length,json=dataLength,proto3" json:"data_length,omitempty"`
	Command    string `protobuf:"bytes,2,opt,name=command,proto3" json:"command,omitempty"`
}

func (x *GameProtocolHeader) Reset() {
	*x = GameProtocolHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_protocol_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameProtocolHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameProtocolHeader) ProtoMessage() {}

func (x *GameProtocolHeader) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_protocol_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameProtocolHeader.ProtoReflect.Descriptor instead.
func (*GameProtocolHeader) Descriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *GameProtocolHeader) GetDataLength() uint32 {
	if x != nil {
		return x.DataLength
	}
	return 0
}

func (x *GameProtocolHeader) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

type PlayerPov struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Team_1Score  uint32      `protobuf:"varint,1,opt,name=team_1_score,json=team1Score,proto3" json:"team_1_score,omitempty"`
	Team_2Score  uint32      `protobuf:"varint,2,opt,name=team_2_score,json=team2Score,proto3" json:"team_2_score,omitempty"`
	Team_1Points uint32      `protobuf:"varint,3,opt,name=team_1_points,json=team1Points,proto3" json:"team_1_points,omitempty"`
	Team_2Points uint32      `protobuf:"varint,4,opt,name=team_2_points,json=team2Points,proto3" json:"team_2_points,omitempty"`
	HandCards    []*HandCard `protobuf:"bytes,5,rep,name=hand_cards,json=handCards,proto3" json:"hand_cards,omitempty"`
	PlayedCards  []*Card     `protobuf:"bytes,6,rep,name=played_cards,json=playedCards,proto3" json:"played_cards,omitempty"`
	Auction      *Auction    `protobuf:"bytes,7,opt,name=auction,proto3,oneof" json:"auction,omitempty"`
	Trump        *CardSuit   `protobuf:"varint,8,opt,name=trump,proto3,enum=protocol.CardSuit,oneof" json:"trump,omitempty"`
	CheatButton  bool        `protobuf:"varint,9,opt,name=cheat_button,json=cheatButton,proto3" json:"cheat_button,omitempty"`
}

func (x *PlayerPov) Reset() {
	*x = PlayerPov{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_protocol_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerPov) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPov) ProtoMessage() {}

func (x *PlayerPov) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_protocol_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPov.ProtoReflect.Descriptor instead.
func (*PlayerPov) Descriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerPov) GetTeam_1Score() uint32 {
	if x != nil {
		return x.Team_1Score
	}
	return 0
}

func (x *PlayerPov) GetTeam_2Score() uint32 {
	if x != nil {
		return x.Team_2Score
	}
	return 0
}

func (x *PlayerPov) GetTeam_1Points() uint32 {
	if x != nil {
		return x.Team_1Points
	}
	return 0
}

func (x *PlayerPov) GetTeam_2Points() uint32 {
	if x != nil {
		return x.Team_2Points
	}
	return 0
}

func (x *PlayerPov) GetHandCards() []*HandCard {
	if x != nil {
		return x.HandCards
	}
	return nil
}

func (x *PlayerPov) GetPlayedCards() []*Card {
	if x != nil {
		return x.PlayedCards
	}
	return nil
}

func (x *PlayerPov) GetAuction() *Auction {
	if x != nil {
		return x.Auction
	}
	return nil
}

func (x *PlayerPov) GetTrump() CardSuit {
	if x != nil && x.Trump != nil {
		return *x.Trump
	}
	return CardSuit_ROSU
}

func (x *PlayerPov) GetCheatButton() bool {
	if x != nil {
		return x.CheatButton
	}
	return false
}

type Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Suit  CardSuit  `protobuf:"varint,1,opt,name=suit,proto3,enum=protocol.CardSuit" json:"suit,omitempty"`
	Value CardValue `protobuf:"varint,2,opt,name=value,proto3,enum=protocol.CardValue" json:"value,omitempty"`
}

func (x *Card) Reset() {
	*x = Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_protocol_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_protocol_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Card.ProtoReflect.Descriptor instead.
func (*Card) Descriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *Card) GetSuit() CardSuit {
	if x != nil {
		return x.Suit
	}
	return CardSuit_ROSU
}

func (x *Card) GetValue() CardValue {
	if x != nil {
		return x.Value
	}
	return CardValue_ACE
}

type HandCard struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Card  *Card     `protobuf:"bytes,1,opt,name=card,proto3" json:"card,omitempty"`
	State CardState `protobuf:"varint,2,opt,name=state,proto3,enum=protocol.CardState" json:"state,omitempty"`
}

func (x *HandCard) Reset() {
	*x = HandCard{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_protocol_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandCard) ProtoMessage() {}

func (x *HandCard) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_protocol_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandCard.ProtoReflect.Descriptor instead.
func (*HandCard) Descriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *HandCard) GetCard() *Card {
	if x != nil {
		return x.Card
	}
	return nil
}

func (x *HandCard) GetState() CardState {
	if x != nil {
		return x.State
	}
	return CardState_DISABLED
}

type Auction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Visible bool   `protobuf:"varint,1,opt,name=visible,proto3" json:"visible,omitempty"`
	Bids    []*Bid `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	MaxBid  uint32 `protobuf:"varint,3,opt,name=max_bid,json=maxBid,proto3" json:"max_bid,omitempty"`
}

func (x *Auction) Reset() {
	*x = Auction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_protocol_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auction) ProtoMessage() {}

func (x *Auction) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_protocol_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auction.ProtoReflect.Descriptor instead.
func (*Auction) Descriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *Auction) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Auction) GetBids() []*Bid {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *Auction) GetMaxBid() uint32 {
	if x != nil {
		return x.MaxBid
	}
	return 0
}

type Bid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HasBid bool   `protobuf:"varint,1,opt,name=has_bid,json=hasBid,proto3" json:"has_bid,omitempty"`
	Value  uint32 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Bid) Reset() {
	*x = Bid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_game_protocol_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bid) ProtoMessage() {}

func (x *Bid) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_game_protocol_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bid.ProtoReflect.Descriptor instead.
func (*Bid) Descriptor() ([]byte, []int) {
	return file_protocol_game_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *Bid) GetHasBid() bool {
	if x != nil {
		return x.HasBid
	}
	return false
}

func (x *Bid) GetValue() uint32 {
	if x != nil {
		return x.Value
	}
	return 0
}

var File_protocol_game_protocol_proto protoreflect.FileDescriptor

var file_protocol_game_protocol_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x4a, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x34,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x22, 0x7e, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x12, 0x34, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x32, 0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x70, 0x6f, 0x76, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x50, 0x6f, 0x76, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x50, 0x6f, 0x76, 0x22, 0x4f, 0x0a, 0x12, 0x47, 0x61, 0x6d, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1f, 0x0a, 0x0b, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0a, 0x64, 0x61, 0x74, 0x61, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x22, 0x97, 0x03, 0x0a, 0x09, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x50, 0x6f, 0x76, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x31, 0x5f, 0x73, 0x63,
	0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x65, 0x61, 0x6d, 0x31,
	0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x32, 0x5f,
	0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x65, 0x61,
	0x6d, 0x32, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x65, 0x61, 0x6d, 0x5f,
	0x31, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b,
	0x74, 0x65, 0x61, 0x6d, 0x31, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x22, 0x0a, 0x0d, 0x74,
	0x65, 0x61, 0x6d, 0x5f, 0x32, 0x5f, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x0b, 0x74, 0x65, 0x61, 0x6d, 0x32, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12,
	0x31, 0x0a, 0x0a, 0x68, 0x61, 0x6e, 0x64, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x73, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x48,
	0x61, 0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x52, 0x09, 0x68, 0x61, 0x6e, 0x64, 0x43, 0x61, 0x72,
	0x64, 0x73, 0x12, 0x31, 0x0a, 0x0c, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64, 0x5f, 0x63, 0x61, 0x72,
	0x64, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x52, 0x0b, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x64,
	0x43, 0x61, 0x72, 0x64, 0x73, 0x12, 0x30, 0x0a, 0x07, 0x61, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x07, 0x61, 0x75, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x2d, 0x0a, 0x05, 0x74, 0x72, 0x75, 0x6d, 0x70,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x75, 0x69, 0x74, 0x48, 0x01, 0x52, 0x05, 0x74, 0x72,
	0x75, 0x6d, 0x70, 0x88, 0x01, 0x01, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x68, 0x65, 0x61, 0x74, 0x5f,
	0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x63, 0x68,
	0x65, 0x61, 0x74, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x61, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x74, 0x72, 0x75, 0x6d, 0x70, 0x22,
	0x59, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64, 0x12, 0x26, 0x0a, 0x04, 0x73, 0x75, 0x69, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x75, 0x69, 0x74, 0x52, 0x04, 0x73, 0x75, 0x69, 0x74, 0x12,
	0x29, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x59, 0x0a, 0x08, 0x48, 0x61,
	0x6e, 0x64, 0x43, 0x61, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x04, 0x63, 0x61, 0x72, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x43, 0x61, 0x72, 0x64, 0x52, 0x04, 0x63, 0x61, 0x72, 0x64, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x22, 0x5f, 0x0a, 0x07, 0x41, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x18, 0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x62, 0x69,
	0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x2e, 0x42, 0x69, 0x64, 0x52, 0x04, 0x62, 0x69, 0x64, 0x73, 0x12, 0x17, 0x0a,
	0x07, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06,
	0x6d, 0x61, 0x78, 0x42, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x03, 0x42, 0x69, 0x64, 0x12, 0x17, 0x0a,
	0x07, 0x68, 0x61, 0x73, 0x5f, 0x62, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x68, 0x61, 0x73, 0x42, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x35, 0x0a, 0x08,
	0x43, 0x61, 0x72, 0x64, 0x53, 0x75, 0x69, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x52, 0x4f, 0x53, 0x55,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x55, 0x42, 0x41, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x56, 0x45, 0x52, 0x44, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x48, 0x49, 0x4e, 0x44,
	0x41, 0x10, 0x03, 0x2a, 0x46, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x07, 0x0a, 0x03, 0x41, 0x43, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x54, 0x45, 0x4e,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4b, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05,
	0x51, 0x55, 0x45, 0x45, 0x4e, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x4a, 0x41, 0x43, 0x4b, 0x10,
	0x04, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x49, 0x4e, 0x45, 0x10, 0x05, 0x2a, 0x26, 0x0a, 0x09, 0x43,
	0x61, 0x72, 0x64, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x41,
	0x42, 0x4c, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x4e, 0x41, 0x42, 0x4c, 0x45,
	0x44, 0x10, 0x01, 0x42, 0x24, 0x5a, 0x22, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protocol_game_protocol_proto_rawDescOnce sync.Once
	file_protocol_game_protocol_proto_rawDescData = file_protocol_game_protocol_proto_rawDesc
)

func file_protocol_game_protocol_proto_rawDescGZIP() []byte {
	file_protocol_game_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_game_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_game_protocol_proto_rawDescData)
	})
	return file_protocol_game_protocol_proto_rawDescData
}

var file_protocol_game_protocol_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_protocol_game_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_protocol_game_protocol_proto_goTypes = []interface{}{
	(CardSuit)(0),              // 0: protocol.CardSuit
	(CardValue)(0),             // 1: protocol.CardValue
	(CardState)(0),             // 2: protocol.CardState
	(*GameServerProtocol)(nil), // 3: protocol.GameServerProtocol
	(*GameClientProtocol)(nil), // 4: protocol.GameClientProtocol
	(*GameProtocolHeader)(nil), // 5: protocol.GameProtocolHeader
	(*PlayerPov)(nil),          // 6: protocol.PlayerPov
	(*Card)(nil),               // 7: protocol.Card
	(*HandCard)(nil),           // 8: protocol.HandCard
	(*Auction)(nil),            // 9: protocol.Auction
	(*Bid)(nil),                // 10: protocol.Bid
}
var file_protocol_game_protocol_proto_depIdxs = []int32{
	5,  // 0: protocol.GameServerProtocol.header:type_name -> protocol.GameProtocolHeader
	5,  // 1: protocol.GameClientProtocol.header:type_name -> protocol.GameProtocolHeader
	6,  // 2: protocol.GameClientProtocol.player_pov:type_name -> protocol.PlayerPov
	8,  // 3: protocol.PlayerPov.hand_cards:type_name -> protocol.HandCard
	7,  // 4: protocol.PlayerPov.played_cards:type_name -> protocol.Card
	9,  // 5: protocol.PlayerPov.auction:type_name -> protocol.Auction
	0,  // 6: protocol.PlayerPov.trump:type_name -> protocol.CardSuit
	0,  // 7: protocol.Card.suit:type_name -> protocol.CardSuit
	1,  // 8: protocol.Card.value:type_name -> protocol.CardValue
	7,  // 9: protocol.HandCard.card:type_name -> protocol.Card
	2,  // 10: protocol.HandCard.state:type_name -> protocol.CardState
	10, // 11: protocol.Auction.bids:type_name -> protocol.Bid
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_protocol_game_protocol_proto_init() }
func file_protocol_game_protocol_proto_init() {
	if File_protocol_game_protocol_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_game_protocol_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameServerProtocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_protocol_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameClientProtocol); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_protocol_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameProtocolHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_protocol_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerPov); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_protocol_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_protocol_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandCard); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_protocol_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_game_protocol_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocol_game_protocol_proto_msgTypes[3].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_game_protocol_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_game_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_game_protocol_proto_depIdxs,
		EnumInfos:         file_protocol_game_protocol_proto_enumTypes,
		MessageInfos:      file_protocol_game_protocol_proto_msgTypes,
	}.Build()
	File_protocol_game_protocol_proto = out.File
	file_protocol_game_protocol_proto_rawDesc = nil
	file_protocol_game_protocol_proto_goTypes = nil
	file_protocol_game_protocol_proto_depIdxs = nil
}
