// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file table.proto (package cruce, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateTableRequest, CreateTableResponse, GetTableRequest, GetTableResponse, JoinTableRequest, JoinTableResponse, LeaveTableRequest, LeaveTableResponse, ListAllTablesRequest, ListAllTablesResponse } from "./table_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service cruce.TableService
 */
export const TableService = {
  typeName: "cruce.TableService",
  methods: {
    /**
     * @generated from rpc cruce.TableService.Create
     */
    create: {
      name: "Create",
      I: CreateTableRequest,
      O: CreateTableResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cruce.TableService.Join
     */
    join: {
      name: "Join",
      I: JoinTableRequest,
      O: JoinTableResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cruce.TableService.Leave
     */
    leave: {
      name: "Leave",
      I: LeaveTableRequest,
      O: LeaveTableResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cruce.TableService.Get
     */
    get: {
      name: "Get",
      I: GetTableRequest,
      O: GetTableResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cruce.TableService.ListAll
     */
    listAll: {
      name: "ListAll",
      I: ListAllTablesRequest,
      O: ListAllTablesResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

