// @generated by protoc-gen-es v1.8.0 with parameter "target=ts"
// @generated from file protocol/game/protocol.proto (package protocol, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum protocol.CardSuit
 */
export enum CardSuit {
  /**
   * @generated from enum value: ROSU = 0;
   */
  ROSU = 0,

  /**
   * @generated from enum value: DUBA = 1;
   */
  DUBA = 1,

  /**
   * @generated from enum value: VERDE = 2;
   */
  VERDE = 2,

  /**
   * @generated from enum value: GHINDA = 3;
   */
  GHINDA = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(CardSuit)
proto3.util.setEnumType(CardSuit, "protocol.CardSuit", [
  { no: 0, name: "ROSU" },
  { no: 1, name: "DUBA" },
  { no: 2, name: "VERDE" },
  { no: 3, name: "GHINDA" },
]);

/**
 * @generated from enum protocol.CardValue
 */
export enum CardValue {
  /**
   * @generated from enum value: ACE = 0;
   */
  ACE = 0,

  /**
   * @generated from enum value: TEN = 1;
   */
  TEN = 1,

  /**
   * @generated from enum value: KING = 2;
   */
  KING = 2,

  /**
   * @generated from enum value: QUEEN = 3;
   */
  QUEEN = 3,

  /**
   * @generated from enum value: JACK = 4;
   */
  JACK = 4,

  /**
   * @generated from enum value: NINE = 5;
   */
  NINE = 5,
}
// Retrieve enum metadata with: proto3.getEnumType(CardValue)
proto3.util.setEnumType(CardValue, "protocol.CardValue", [
  { no: 0, name: "ACE" },
  { no: 1, name: "TEN" },
  { no: 2, name: "KING" },
  { no: 3, name: "QUEEN" },
  { no: 4, name: "JACK" },
  { no: 5, name: "NINE" },
]);

/**
 * @generated from enum protocol.CardState
 */
export enum CardState {
  /**
   * @generated from enum value: DISABLED = 0;
   */
  DISABLED = 0,

  /**
   * @generated from enum value: ENABLED = 1;
   */
  ENABLED = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(CardState)
proto3.util.setEnumType(CardState, "protocol.CardState", [
  { no: 0, name: "DISABLED" },
  { no: 1, name: "ENABLED" },
]);

/**
 * @generated from message protocol.GameServerProtocol
 */
export class GameServerProtocol extends Message<GameServerProtocol> {
  /**
   * @generated from field: protocol.GameProtocolHeader header = 1;
   */
  header?: GameProtocolHeader;

  constructor(data?: PartialMessage<GameServerProtocol>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "protocol.GameServerProtocol";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "header", kind: "message", T: GameProtocolHeader },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameServerProtocol {
    return new GameServerProtocol().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameServerProtocol {
    return new GameServerProtocol().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameServerProtocol {
    return new GameServerProtocol().fromJsonString(jsonString, options);
  }

  static equals(a: GameServerProtocol | PlainMessage<GameServerProtocol> | undefined, b: GameServerProtocol | PlainMessage<GameServerProtocol> | undefined): boolean {
    return proto3.util.equals(GameServerProtocol, a, b);
  }
}

/**
 * @generated from message protocol.GameClientProtocol
 */
export class GameClientProtocol extends Message<GameClientProtocol> {
  /**
   * @generated from field: protocol.GameProtocolHeader header = 1;
   */
  header?: GameProtocolHeader;

  /**
   * @generated from field: protocol.PlayerPov player_pov = 2;
   */
  playerPov?: PlayerPov;

  constructor(data?: PartialMessage<GameClientProtocol>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "protocol.GameClientProtocol";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "header", kind: "message", T: GameProtocolHeader },
    { no: 2, name: "player_pov", kind: "message", T: PlayerPov },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameClientProtocol {
    return new GameClientProtocol().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameClientProtocol {
    return new GameClientProtocol().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameClientProtocol {
    return new GameClientProtocol().fromJsonString(jsonString, options);
  }

  static equals(a: GameClientProtocol | PlainMessage<GameClientProtocol> | undefined, b: GameClientProtocol | PlainMessage<GameClientProtocol> | undefined): boolean {
    return proto3.util.equals(GameClientProtocol, a, b);
  }
}

/**
 * @generated from message protocol.GameProtocolHeader
 */
export class GameProtocolHeader extends Message<GameProtocolHeader> {
  /**
   * @generated from field: uint32 data_length = 1;
   */
  dataLength = 0;

  /**
   * @generated from field: string command = 2;
   */
  command = "";

  constructor(data?: PartialMessage<GameProtocolHeader>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "protocol.GameProtocolHeader";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "data_length", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "command", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GameProtocolHeader {
    return new GameProtocolHeader().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GameProtocolHeader {
    return new GameProtocolHeader().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GameProtocolHeader {
    return new GameProtocolHeader().fromJsonString(jsonString, options);
  }

  static equals(a: GameProtocolHeader | PlainMessage<GameProtocolHeader> | undefined, b: GameProtocolHeader | PlainMessage<GameProtocolHeader> | undefined): boolean {
    return proto3.util.equals(GameProtocolHeader, a, b);
  }
}

/**
 * @generated from message protocol.PlayerPov
 */
export class PlayerPov extends Message<PlayerPov> {
  /**
   * @generated from field: uint32 team_1_score = 1;
   */
  team1Score = 0;

  /**
   * @generated from field: uint32 team_2_score = 2;
   */
  team2Score = 0;

  /**
   * @generated from field: uint32 team_1_points = 3;
   */
  team1Points = 0;

  /**
   * @generated from field: uint32 team_2_points = 4;
   */
  team2Points = 0;

  /**
   * @generated from field: repeated protocol.HandCard hand_cards = 5;
   */
  handCards: HandCard[] = [];

  /**
   * @generated from field: repeated protocol.Card played_cards = 6;
   */
  playedCards: Card[] = [];

  /**
   * @generated from field: optional protocol.Auction auction = 7;
   */
  auction?: Auction;

  /**
   * @generated from field: optional protocol.CardSuit trump = 8;
   */
  trump?: CardSuit;

  /**
   * @generated from field: bool cheat_button = 9;
   */
  cheatButton = false;

  constructor(data?: PartialMessage<PlayerPov>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "protocol.PlayerPov";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "team_1_score", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 2, name: "team_2_score", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 3, name: "team_1_points", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 4, name: "team_2_points", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "hand_cards", kind: "message", T: HandCard, repeated: true },
    { no: 6, name: "played_cards", kind: "message", T: Card, repeated: true },
    { no: 7, name: "auction", kind: "message", T: Auction, opt: true },
    { no: 8, name: "trump", kind: "enum", T: proto3.getEnumType(CardSuit), opt: true },
    { no: 9, name: "cheat_button", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PlayerPov {
    return new PlayerPov().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PlayerPov {
    return new PlayerPov().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PlayerPov {
    return new PlayerPov().fromJsonString(jsonString, options);
  }

  static equals(a: PlayerPov | PlainMessage<PlayerPov> | undefined, b: PlayerPov | PlainMessage<PlayerPov> | undefined): boolean {
    return proto3.util.equals(PlayerPov, a, b);
  }
}

/**
 * @generated from message protocol.Card
 */
export class Card extends Message<Card> {
  /**
   * @generated from field: protocol.CardSuit suit = 1;
   */
  suit = CardSuit.ROSU;

  /**
   * @generated from field: protocol.CardValue value = 2;
   */
  value = CardValue.ACE;

  constructor(data?: PartialMessage<Card>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "protocol.Card";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "suit", kind: "enum", T: proto3.getEnumType(CardSuit) },
    { no: 2, name: "value", kind: "enum", T: proto3.getEnumType(CardValue) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Card {
    return new Card().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Card {
    return new Card().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Card {
    return new Card().fromJsonString(jsonString, options);
  }

  static equals(a: Card | PlainMessage<Card> | undefined, b: Card | PlainMessage<Card> | undefined): boolean {
    return proto3.util.equals(Card, a, b);
  }
}

/**
 * @generated from message protocol.HandCard
 */
export class HandCard extends Message<HandCard> {
  /**
   * @generated from field: protocol.Card card = 1;
   */
  card?: Card;

  /**
   * @generated from field: protocol.CardState state = 2;
   */
  state = CardState.DISABLED;

  constructor(data?: PartialMessage<HandCard>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "protocol.HandCard";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "card", kind: "message", T: Card },
    { no: 2, name: "state", kind: "enum", T: proto3.getEnumType(CardState) },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): HandCard {
    return new HandCard().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): HandCard {
    return new HandCard().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): HandCard {
    return new HandCard().fromJsonString(jsonString, options);
  }

  static equals(a: HandCard | PlainMessage<HandCard> | undefined, b: HandCard | PlainMessage<HandCard> | undefined): boolean {
    return proto3.util.equals(HandCard, a, b);
  }
}

/**
 * @generated from message protocol.Auction
 */
export class Auction extends Message<Auction> {
  /**
   * @generated from field: bool visible = 1;
   */
  visible = false;

  /**
   * @generated from field: repeated protocol.Bid bids = 2;
   */
  bids: Bid[] = [];

  /**
   * @generated from field: uint32 max_bid = 3;
   */
  maxBid = 0;

  constructor(data?: PartialMessage<Auction>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "protocol.Auction";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "visible", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "bids", kind: "message", T: Bid, repeated: true },
    { no: 3, name: "max_bid", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Auction {
    return new Auction().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Auction {
    return new Auction().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Auction {
    return new Auction().fromJsonString(jsonString, options);
  }

  static equals(a: Auction | PlainMessage<Auction> | undefined, b: Auction | PlainMessage<Auction> | undefined): boolean {
    return proto3.util.equals(Auction, a, b);
  }
}

/**
 * @generated from message protocol.Bid
 */
export class Bid extends Message<Bid> {
  /**
   * @generated from field: bool has_bid = 1;
   */
  hasBid = false;

  /**
   * @generated from field: uint32 value = 2;
   */
  value = 0;

  constructor(data?: PartialMessage<Bid>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "protocol.Bid";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "has_bid", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "value", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Bid {
    return new Bid().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Bid {
    return new Bid().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Bid {
    return new Bid().fromJsonString(jsonString, options);
  }

  static equals(a: Bid | PlainMessage<Bid> | undefined, b: Bid | PlainMessage<Bid> | undefined): boolean {
    return proto3.util.equals(Bid, a, b);
  }
}

